name: Transfer All Secrets

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Nombre del repositorio destino en formato owner/repo'
        required: true
        default: 'edwingr93/repo-destino'

jobs:
  transfer-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate with GitHub CLI
      run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token

    - name: List and transfer secrets
      run: |
        # Get the list of secrets in the source repo
        secrets=$(gh secret list --repo ${{ github.repository }} --json name --jq '.[].name')

        # Loop through each secret and set it in the target repo
        for secret in $secrets; do
          secret_value=$(gh secret get "$secret" --repo ${{ github.repository }})
          gh secret set "$secret" --repo ${{ github.event.inputs.target_repo }} <<< "$secret_value"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
