name: Inject Secrets

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Nombre del repositorio destino en formato owner/repo'
        required: true
        default: 'edwingr93/repo-destino'
        
jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate with GitHub CLI
      run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token

    - name: Inject secrets into target repo
      run: |
        echo "${{ secrets.MY_SECRET }}" | gh secret set MY_SECRET --repo ${{ github.event.inputs.target_repo }}
        echo "${{ secrets.MY_SECRET2 }}" | gh secret set MY_SECRET2 --repo ${{ github.event.inputs.target_repo }}
        echo "${{ secrets.MY_SECRET2 }}" | gh variable set MY_SECRET2 --repo ${{ github.event.inputs.target_repo }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.target_repo }} # Reemplaza con el nombre del repositorio objetivo
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Use variable and inject it into target repository
      run: |
          # Aquí puedes utilizar la variable directamente. Ejemplo:
          echo "MY_VARIABLE=${{ vars.NAME }}" >> .env # Ajusta esto según tu necesidad
          
          git add .env
          git commit -m "Add environment variable"
          git push origin main
      env:
          VARIABLE1: ${{ vars.NAME }}
